<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scopeName</key>
    <string>source.dftemplate</string>
    <key>fileTypes</key>
    <array>
        <string>dftemplate</string>
    </array>
    <key>name</key>
    <string>DfTemplate</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#comments</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#literals</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#keywords</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#symbols</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#symbol-definition</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#tasks</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>^(-)+.*$</string>
                    <key>name</key>
                    <string>comment.line.double-dash.dftemplate</string>
                </dict>
            </array>
        </dict>
        <key>literals</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b([0-9_]+|([0-9_]+)?\.[0-9_]+)\b</string>
                    <key>name</key>
                    <string>constant.numeric.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>&lt;(ce|---)&gt;</string>
                    <key>name</key>
                    <string>string.unquoted.dftemplate</string>
                </dict>
            </array>
        </dict>
        <key>keywords</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(Quest:)\s+(\w+)\b</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>markup.heading.dftemplate</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>string.unquoted.dftemplate</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>match</key>
                    <string>DisplayName:</string>
                    <key>name</key>
                    <string>markup.heading.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(^|\s)(Messages:|QRC:|QBN:)\s</string>
                    <key>name</key>
                    <string>markup.heading.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(^|\s)(QuestorOffer:|RefuseQuest:|AcceptQuest:|QuestComplete:|RumorsDuringQuest:|RumorsPostFailure:|RumorsPostSuccess:|QuestorPostSuccess:|QuestorPostFailure:|QuestLogEntry:|Message:)\s</string>
                    <key>name</key>
                    <string>keyword.control.message.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\((keyword|message|definition|symbol)\)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.dftemplate</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\((condition|action)\)\s(\w+)\s-></string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.dftemplate</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>support.type.dftemplate</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>symbols</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>((?&lt;=\s)|(?&lt;=^))%(\w|\.\d)+(?=\b)</string>
                    <key>name</key>
                    <string>variable.language.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>((?&lt;=\s)|(?&lt;=^))(_{1,4}|={1,2})(\w|\.\d)+_(?=\b)</string>
                    <key>name</key>
                    <string>variable.other.symbol.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?&lt;=\s)&amp;[0-9]+(?=\s)</string>
                    <key>name</key>
                    <string>variable.parameter.macro.dftemplate</string>
                </dict>
            </array>
        </dict>
        <key>symbol-definition</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>\b(Item|Person|Place|Clock|Foe|variable)\b</string>
                    <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.symbol.dftemplate</string>
                            </dict>
                        </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#symbols</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#literals</string>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\b(range|to|artifact|item|class|subclass|named|atHome|face|factionType|group|faction|male|female|permanent|local|remote|is)\b</string>
                            <key>name</key>
                            <string>support.type.attribute.dftemplate</string>
                        </dict>	
                    </array>
                    <key>end</key>
                    <string>$</string>
                </dict>
            </array>
        </dict>
        <key>tasks</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>^\s*until</string>
                    <key>name</key>
                    <string>support.function.task.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(task|performed):(?=\s*$)</string>
                    <key>name</key>
                    <string>support.function.task.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(^|\s|&lt;)src:\s+[^\s&gt;]+(\s|&gt;)</string>
                    <key>name</key>
                    <string>meta.preprocessor.define.src-directive.dftemplate</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(macro)\s+(\w+)\b</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.macro.dftemplate</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.macro.dftemplate</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\bend\s+macro\b</string>
                    <key>name</key>
                    <string>keyword.control.macro.dftemplate</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=->)|(?&lt;=^)\s*(?=when( not)? [a-zA-Z0-9_.]+( (and|or)( not)? [a-zA-Z0-9_.]+)*\s*$)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#symbols</string>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\s(and not|and|or not|or)\s</string>
                            <key>name</key>
                            <string>keyword.control.operator.conditional.dftemplate</string>
                        </dict>	
                    </array>
                    <key>end</key>
                    <string>$</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(start\squest)\s([^\s]+)\b</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.start-quest.dftemplate</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.class.quest.dftemplate</string>
                        </dict>
                    </dict>
                </dict>		
                <dict>
                    <key>match</key>
                    <string>\bend\squest\b</string>
                    <key>name</key>
                    <string>keyword.control.end-quest.dftemplate</string>
                </dict>				
            </array>
        </dict>
    </dict>
</dict>
</plist>